name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            echo "package-lock.json found, running npm ci"
            npm ci --prefer-offline --no-audit
          else
            echo "package-lock.json not found, running npm install"
            npm install --no-audit --prefer-offline
          fi

      - name: Build
        run: npm run build --if-present

      - name: Run tests (Karma)
        env:
          CI: true
        run: |
          npm run test -- --watch=false --browsers=ChromeHeadless
