name: CI and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --prefer-offline --no-audit
          else
            npm install --no-audit --prefer-offline
          fi

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        env:
          CI: true
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Show dist (debug)
        run: |
          echo "dist contents:"
          ls -la dist || true

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: dist

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Set git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add Heroku remote
        run: |
          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}

      - name: Push dist to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          set -e
          if [ -d dist ]; then
            echo "Pushing dist/ to Heroku (using subtree or fallback)"
            git add -f dist || true
            git commit -m "chore(deploy): dist" || true
            if git ls-tree --name-only -r HEAD | grep -q "^dist/"; then
              git subtree push --prefix dist heroku main || true
            fi
            pushd dist
            git init
            git add -A
            git commit -m "deploy dist" || true
            # Ensure branch 'main' exists (rename default branch if necessary) then push
            git branch -M main || true
            git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git main --force
            popd
          else
            echo "dist/ not found — aborting deploy"
            exit 1
          fi
